{
	"version": 1671219644,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"peer-sheet0.png",
		"host-sheet0.png",
		"host_player-sheet0.png",
		"host_player-sheet1.png",
		"sprite-sheet0.png",
		"ezgifcomgifmaker-sheet0.png",
		"tilemap.png",
		"untitledmm-sheet0.png",
		"notify.m4a",
		"notify.ogg",
		"windows xp startup.m4a",
		"windows xp startup.ogg",
		"new project.ogg",
		"y2mate.is-discord-notification-sound-effect-6qpv9jbfqtg-128k-1643041722501.m4a",
		"y2mate.is-discord-notification-sound-effect-6qpv9jbfqtg-128k-1643041722501.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}